### ISSUE TITLE
Performance of join and groupJoin methods is abnormally bad

### ISSUE THREAD

**Issue by Athari** [TimeToogo/Pinq#22]
Your competitor here. :grinning:

Pinq queries containing `join` and `groupJoin` can be thousands of times slower than native implementation, or any other LINQ library, when long arrays are joined (thousands of items). I have no idea what is going on, as I have trouble navigating your immense code base, but you should probably look into it.

---

I've run the tests, your code is often an order of magnitude slower than YaLinqo, sometimes less, sometimes much more (like in the cases above). See [gist with benchmark results](https://gist.github.com/Athari/1d001fde76f86f219c23) (master branch). I've significantly improved performance of sorting thanks to your implementation. I didn't know `array_multisort` is *so much faster* than `usort` — the difference caused Pinq to be the fastest of the major LINQ libraries in the sorting test (well, no longer so, but it was).

Considering your library is the only one providing LINQ to databases, I think it's critical to avoid performance traps in the basic functionality, even if the library is the slowest of the bunch.

Technically, we aren't even competitors, considering YaLinqo is designed to be fast and expressive LINQ to objects and Pinq is designed to be LINQ to both objects and databases. Functionality and performance is so different that there isn't much to compete over. I'm still surprised by the lack of functionality in the basic methods of Pinq though, but I guess limiting expressiveness is required to make implementing query providers actually possible.

What is the current state of MySQL query provider? Your website and readme say that it's a "demo", so I'm curious what plans you have on implementing production-ready query providers.

By the way, how did you manage to receive more than 200 stars on GitHub? Did SitePoint cause so much traffic or is it something else?

Anyway, thanks for writing your library. Ginq and Pinq forced me to update my own library: add missing methods, improve peformance, add integartion with CI and code quality tools. :grinning:

**Comment by TimeToogo** [comment]
Hi Athari,

First and foremost, thank you for creating these benchmarks and highlighting the performance concerns and apologies for not responding sooner. I have identified the large oversight on my part causing the abhorrent performance of `join` and `groupJoin` operations. The issue was that the inner value lookup was being recreated on every iteration rather then once at the beginning. This has been fixed and released as **3.2.1**. Hopefully the benchmarks will be somewhat comparable with this release.

Anyways, I am not investigating possible avenues of increasing the performance of PINQ. I think one of the main reasons the implementation tends to be slower is that it is compatible with PHP 5.4 and hence tries to cover all the edge cases due to the support of non scalar keys. I will have to re-evaluate this for performance reasons.

With regards to a LINQ to databases implementation, it is definitely something that I have worked on and hope to continue working on but lately it has become difficult to find the time required. Hopefully this will not be a problem sometime from now.

I originally posted this project on the [PHP subreddit](https://www.reddit.com/r/PHP/) where it got a bit of exposure but I believe that most people have found it through other references as you have mentioned.

I am glad to hear that you have updated your project with open source tooling and once again your benchmarking has highlighted areas for improvement in PINQ. Seems some competition will benefit everyone :grinning:. Best of luck with YaLinqo.

**Comment by staabm** [comment]
@Athari could you re-run your benchmark using a recent release?

**Comment by Athari** [comment]
@staabm https://gist.github.com/Athari/1d001fde76f86f219c23 See revision history to compare the results, I've only updated the lines which changed considerably.

Massive improvements in several tests, there're no crazy results in the "5000 times slower" range now. Pinq is also faster than Ginq in more tests, sometimes significantly faster (I see several commits improving performance). Joining arrays and custom aggregation are still much slower than the rest of the libraries though. And YaLinqo remains the fastest, obviously.
